# Generated by Django 4.1 on 2022-09-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
