# Generated by Django 4.1 on 2022-09-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="language",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
