# Generated by Django 4.1 on 2022-09-03 18:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WordDict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=1000)),
                ("type", models.CharField(max_length=1000)),
                (
                    "description",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=1000),
                        size=None,
                    ),
                ),
                (
                    "similars",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=1000),
                        size=None,
                    ),
                ),
                (
                    "antonyms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=1000),
                        size=None,
                    ),
                ),
            ],
        ),
    ]
