# Generated by Django 4.1 on 2022-10-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dictionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=1000)),
                ("type", models.CharField(max_length=1000)),
                ("description", models.CharField(blank=True, max_length=1000)),
                ("example", models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                "verbose_name": "dictionary",
                "verbose_name_plural": "dictionaries",
                "ordering": ["word"],
            },
        ),
        migrations.CreateModel(
            name="Languages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("eng_name", models.CharField(max_length=100)),
                ("native_name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "language",
                "verbose_name_plural": "languages",
                "ordering": ["code"],
            },
        ),
    ]
