# Generated by Django 4.1 on 2022-09-03 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WordDict",
            new_name="Dictionary",
        ),
    ]
