# Generated by Django 4.1 on 2022-10-05 15:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Synonmys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=1000, null=True)),
                (
                    "words",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10000),
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "dictionary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_page.dictionary",
                    ),
                ),
            ],
        ),
    ]
