# Generated by Django 4.1 on 2022-10-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0002_synonmys"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Synonmys",
            new_name="Synonyms",
        ),
    ]
