# Generated by Django 4.1 on 2022-09-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0003_alter_dictionary_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dictionary",
            options={
                "ordering": ["word"],
                "verbose_name": "dictionary",
                "verbose_name_plural": "dictionaries",
            },
        ),
        migrations.RemoveField(
            model_name="dictionary",
            name="antonyms",
        ),
        migrations.RemoveField(
            model_name="dictionary",
            name="similars",
        ),
        migrations.AddField(
            model_name="dictionary",
            name="example",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="description",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
