# Generated by Django 4.1 on 2022-09-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_page",
            "0004_alter_dictionary_options_remove_dictionary_antonyms_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dictionary",
            name="example",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
