# Generated by Django 4.1 on 2022-09-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0005_alter_dictionary_example"),
    ]

    operations = [
        migrations.CreateModel(
            name="Languages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("eng_name", models.CharField(max_length=100)),
                ("native_name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "language",
                "verbose_name_plural": "languages",
                "ordering": ["code"],
            },
        ),
    ]
