# Generated by Django 4.1 on 2022-09-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0006_languages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="languages",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
