# Generated by Django 4.1 on 2022-09-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main_page", "0002_rename_worddict_dictionary"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordLists",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("list_name", models.CharField(max_length=50, unique=True)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("word", models.ManyToManyField(null=True, to="main_page.dictionary")),
            ],
            options={
                "ordering": ["list_name"],
            },
        ),
    ]
