# Generated by Django 4.1 on 2022-10-03 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("word_lists", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscribedList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "words_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="word_lists.wordslist",
                    ),
                ),
            ],
            options={
                "verbose_name": "subscribed_list",
                "verbose_name_plural": "subscribed_lists",
            },
        ),
    ]
