# Generated by Django 4.1 on 2022-09-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_page", "0002_rename_worddict_dictionary"),
        ("word_lists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordlists",
            name="word",
            field=models.ManyToManyField(to="main_page.dictionary"),
        ),
    ]
