# Generated by Django 4.1 on 2022-10-03 18:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("word_lists", "0002_subscribedlist"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subscribedlist",
            unique_together={("user", "words_list")},
        ),
    ]
