# Generated by Django 4.1 on 2022-10-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("word_lists", "0003_alter_subscribedlist_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wordslist",
            options={
                "ordering": ["created_date"],
                "verbose_name": "words_list",
                "verbose_name_plural": "words_lists",
            },
        ),
    ]
