# Generated by Django 4.1 on 2022-09-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("word_lists", "0004_wordlist_delete_wordlists"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wordlist",
            options={
                "ordering": ["list_name"],
                "verbose_name": "word_list",
                "verbose_name_plural": "word_lists",
            },
        ),
        migrations.AddField(
            model_name="wordlist",
            name="is_private",
            field=models.BooleanField(default=True),
        ),
    ]
