# Generated by Django 4.1 on 2022-09-29 20:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("word_lists", "0005_alter_wordlist_options_wordlist_is_private"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordlist",
            name="words",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(null=True), size=None
            ),
        ),
    ]
