# Generated by Django 4.1 on 2022-10-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("word_lists", "0005_alter_wordslist_share_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wordslist",
            name="words",
        ),
        migrations.AddField(
            model_name="wordslist",
            name="_words",
            field=models.CharField(default=str, max_length=10000),
        ),
    ]
