# Generated by Django 4.1 on 2022-09-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("word_lists", "0006_alter_wordlist_words"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="wordlist",
            constraint=models.UniqueConstraint(
                fields=("list_name", "user"), name="unique_user_list"
            ),
        ),
    ]
