# Generated by Django 4.1 on 2022-09-29 20:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("word_lists", "0007_wordlist_unique_user_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordlist",
            name="words",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), null=True, size=None
            ),
        ),
    ]
