# Generated by Django 4.1 on 2022-09-29 21:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("word_lists", "0008_alter_wordlist_words"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="wordlist",
            name="unique_user_list",
        ),
        migrations.AlterUniqueTogether(
            name="wordlist",
            unique_together={("list_name", "user")},
        ),
    ]
