# Generated by Django 4.1 on 2022-09-29 21:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("word_lists", "0010_alter_wordlist_list_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordlist",
            name="words",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=list, null=True, size=None
            ),
        ),
    ]
