# Generated by Django 4.1 on 2022-10-01 12:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("word_lists", "0012_alter_wordlist_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WordList",
            new_name="WordsList",
        ),
    ]
