# Generated by Django 4.1 on 2022-10-01 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("word_lists", "0013_rename_wordlist_wordslist"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wordslist",
            options={
                "ordering": ["name"],
                "verbose_name": "words_list",
                "verbose_name_plural": "wordslists",
            },
        ),
    ]
