# Generated by Django 4.1 on 2022-10-01 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("word_lists", "0014_alter_wordslist_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wordslist",
            options={
                "ordering": ["name"],
                "verbose_name": "words_list",
                "verbose_name_plural": "words_lists",
            },
        ),
    ]
